// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'panel_model.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_$PanelModelImpl _$$PanelModelImplFromJson(Map<String, dynamic> json) =>
    _$PanelModelImpl(
      sensorId: json['sensor_id'] as String,
      temperature: (json['temperature'] as num).toDouble(),
      totalPowerAmount: json['total_power_amount'] as String,
      lmonthUseAmount: json['lmonth_use_amount'] as String,
      cmonthUseAmount: json['cmonth_use_amount'] as String,
      doorFlag: json['door_flag'] as String,
      heaterCtrFlag: json['heater_ctr_flag'] as String,
      smokeDetectionFlag: json['smoke_detection_flag'] as String,
      arkFlag: json['ark_flag'] as String,
      blackoutFlag: json['blackout_flag'] as String,
      leakageFlag: json['leakage_flag'] as String,
      leakageBreakerPos: json['leakage_breaker_pos'] as String,
      overCurrentFlag: json['overcurrent_flag'] as String,
      overCurrentBreakerPos: json['overcurrent_breaker_pos'] as String,
      lowCurrentFlag: json['lowcurrent_flag'] as String,
      lowCurrentBreakerPos: json['lowcurrent_breaker_pos'] as String,
      rElectricUsage: (json['r_electric_usage'] as num).toDouble(),
      sElectricUsage: (json['s_electric_usage'] as num).toDouble(),
      tElectricUsage: (json['t_electric_usage'] as num).toDouble(),
      wiresOverloadFlag: json['wiresoverload_flag'] as String,
      highTemperatureFlag: json['high_temperature_flag'] as String,
      overloadLine: json['overload_line'] as String,
      rCurrentValue: json['r_current_value'] as String,
      sCurrentValue: json['s_current_value'] as String,
      tCurrentValue: json['t_current_value'] as String,
      rnVoltageValue: json['rn_voltage_value'] as String,
      snVoltageValue: json['sn_voltage_value'] as String,
      tnVoltageValue: json['tn_voltage_value'] as String,
      rsVoltageValue: json['rs_voltage_value'] as String,
      rtVoltageValue: json['rt_voltage_value'] as String,
      stVoltageValue: json['st_voltage_value'] as String,
      hlVoltagePos: json['hl_voltage_pos'] as String,
      breaker: json['breaker'] as String,
      breakerStatus: json['breaker_status'] as String,
      breakerCurrentUsage: json['breaker_current_usage'] as String,
      breakerControlYn: json['breaker_control_yn'] as String,
      ctrlStatus: json['ctrl_status'] as String,
      leakageStatus: json['leakage_status'] as String,
    );

Map<String, dynamic> _$$PanelModelImplToJson(_$PanelModelImpl instance) =>
    <String, dynamic>{
      'sensor_id': instance.sensorId,
      'temperature': instance.temperature,
      'total_power_amount': instance.totalPowerAmount,
      'lmonth_use_amount': instance.lmonthUseAmount,
      'cmonth_use_amount': instance.cmonthUseAmount,
      'door_flag': instance.doorFlag,
      'heater_ctr_flag': instance.heaterCtrFlag,
      'smoke_detection_flag': instance.smokeDetectionFlag,
      'ark_flag': instance.arkFlag,
      'blackout_flag': instance.blackoutFlag,
      'leakage_flag': instance.leakageFlag,
      'leakage_breaker_pos': instance.leakageBreakerPos,
      'overcurrent_flag': instance.overCurrentFlag,
      'overcurrent_breaker_pos': instance.overCurrentBreakerPos,
      'lowcurrent_flag': instance.lowCurrentFlag,
      'lowcurrent_breaker_pos': instance.lowCurrentBreakerPos,
      'r_electric_usage': instance.rElectricUsage,
      's_electric_usage': instance.sElectricUsage,
      't_electric_usage': instance.tElectricUsage,
      'wiresoverload_flag': instance.wiresOverloadFlag,
      'high_temperature_flag': instance.highTemperatureFlag,
      'overload_line': instance.overloadLine,
      'r_current_value': instance.rCurrentValue,
      's_current_value': instance.sCurrentValue,
      't_current_value': instance.tCurrentValue,
      'rn_voltage_value': instance.rnVoltageValue,
      'sn_voltage_value': instance.snVoltageValue,
      'tn_voltage_value': instance.tnVoltageValue,
      'rs_voltage_value': instance.rsVoltageValue,
      'rt_voltage_value': instance.rtVoltageValue,
      'st_voltage_value': instance.stVoltageValue,
      'hl_voltage_pos': instance.hlVoltagePos,
      'breaker': instance.breaker,
      'breaker_status': instance.breakerStatus,
      'breaker_current_usage': instance.breakerCurrentUsage,
      'breaker_control_yn': instance.breakerControlYn,
      'ctrl_status': instance.ctrlStatus,
      'leakage_status': instance.leakageStatus,
    };
