// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALSyLn8vduoON83sER0Y0nZ72lue45ewk',
    appId: '1:958355321259:web:a97a11d0ea769a3a8fa2ee',
    messagingSenderId: '958355321259',
    projectId: 'safeguard-84714',
    authDomain: 'safeguard-84714.firebaseapp.com',
    storageBucket: 'safeguard-84714.firebasestorage.app',
    measurementId: 'G-739XSN778H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArtUO8fN9XuWZyMiXwJXmvlmxE210Lkdk',
    appId: '1:958355321259:android:99fa07c4e3c142fc8fa2ee',
    messagingSenderId: '958355321259',
    projectId: 'safeguard-84714',
    storageBucket: 'safeguard-84714.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQByjcS0yPG2RMkEb_T-Icp7XvJwLw7Y4',
    appId: '1:958355321259:ios:e3b48306dce811548fa2ee',
    messagingSenderId: '958355321259',
    projectId: 'safeguard-84714',
    storageBucket: 'safeguard-84714.firebasestorage.app',
    iosBundleId: 'kr.co.trcs.safeGuard',
  );
}
